// Copyright 2025 The go-a2a Authors
// SPDX-License-Identifier: Apache-2.0

package agent

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"mime"
	"path/filepath"
)

// ContentType represents the type of content within a TranscriptionEntry.
type ContentType int

const (
	// ContentTypeText represents plain text content.
	ContentTypeText ContentType = iota

	// ContentTypeImage represents image data.
	ContentTypeImage

	// ContentTypeAudio represents audio data.
	ContentTypeAudio

	// ContentTypeVideo represents video data.
	ContentTypeVideo
)

// ContentData is an interface for data that can be used in transcription entries.
// This provides flexibility to handle different types of content.
type ContentData interface {
	// Type returns the content type of this data.
	Type() ContentType

	// MimeType returns the MIME type of this content.
	MimeType() string

	// Reader returns a reader to access the content data.
	Reader() io.Reader
}

// BlobData represents binary data with an associated mime type.
type BlobData struct {
	data     []byte
	mimeType string
}

// NewBlobData creates a new BlobData instance from raw bytes and a mime type.
func NewBlobData(data []byte, mimeType string) *BlobData {
	return &BlobData{
		data:     data,
		mimeType: mimeType,
	}
}

// NewBlobDataFromFile creates a new BlobData instance, inferring the mime type
// from the file extension.
func NewBlobDataFromFile(data []byte, filename string) *BlobData {
	mimeType := mime.TypeByExtension(filepath.Ext(filename))
	if mimeType == "" {
		mimeType = "application/octet-stream"
	}
	return &BlobData{
		data:     data,
		mimeType: mimeType,
	}
}

// Type returns the content type based on the MIME type.
func (b *BlobData) Type() ContentType {
	if b.mimeType == "" {
		return ContentTypeText
	}

	switch {
	case bytes.HasPrefix([]byte(b.mimeType), []byte("image/")):
		return ContentTypeImage
	case bytes.HasPrefix([]byte(b.mimeType), []byte("audio/")):
		return ContentTypeAudio
	case bytes.HasPrefix([]byte(b.mimeType), []byte("video/")):
		return ContentTypeVideo
	default:
		return ContentTypeText
	}
}

// MimeType returns the MIME type of this blob.
func (b *BlobData) MimeType() string {
	return b.mimeType
}

// Reader returns a reader to access the blob data.
func (b *BlobData) Reader() io.Reader {
	return bytes.NewReader(b.data)
}

// Data returns the raw data of this blob.
func (b *BlobData) Data() []byte {
	return b.data
}

// TextData represents text content with an optional MIME type.
type TextData struct {
	text     string
	mimeType string
}

// NewTextData creates a new TextData instance.
func NewTextData(text string) *TextData {
	return &TextData{
		text:     text,
		mimeType: "text/plain",
	}
}

// Type always returns ContentTypeText.
func (t *TextData) Type() ContentType {
	return ContentTypeText
}

// MimeType returns the MIME type of this text content.
func (t *TextData) MimeType() string {
	return t.mimeType
}

// Reader returns a reader to access the text data.
func (t *TextData) Reader() io.Reader {
	return bytes.NewReader([]byte(t.text))
}

// Text returns the text content.
func (t *TextData) Text() string {
	return t.text
}

// Role represents the source of the transcription data.
type Role string

const (
	// RoleUser represents content provided by the user.
	RoleUser Role = "user"

	// RoleModel represents content generated by the model.
	RoleModel Role = "model"

	// RoleSystem represents content from the system.
	RoleSystem Role = "system"
)

// TranscriptionEntry stores data that can be used for transcription.
type TranscriptionEntry struct {
	// Role is who created this data, typically "user" or "model"
	role Role

	// Data is the content that can be used for transcription
	data ContentData
}

// NewTranscriptionEntry creates a new TranscriptionEntry with the given role and data.
func NewTranscriptionEntry(role Role, data ContentData) (*TranscriptionEntry, error) {
	if role == "" {
		return nil, errors.New("role cannot be empty")
	}

	if data == nil {
		return nil, errors.New("data cannot be nil")
	}

	return &TranscriptionEntry{
		role: role,
		data: data,
	}, nil
}

// Role returns the role of this transcription entry.
func (t *TranscriptionEntry) Role() Role {
	return t.role
}

// Data returns the content data.
func (t *TranscriptionEntry) Data() ContentData {
	return t.data
}

// String returns a string representation of the transcription entry.
func (t *TranscriptionEntry) String() string {
	contentType := "unknown"
	switch t.data.Type() {
	case ContentTypeText:
		contentType = "text"
	case ContentTypeImage:
		contentType = "image"
	case ContentTypeAudio:
		contentType = "audio"
	case ContentTypeVideo:
		contentType = "video"
	}

	return fmt.Sprintf("TranscriptionEntry{role: %s, type: %s, mime: %s}",
		t.role, contentType, t.data.MimeType())
}
